//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configurations
    {
        public int IdConfiguration { get; set; }
        public string idPlayerOwner { get; set; }
        public string volMusic { get; set; }
        public string volSFX { get; set; }
        public string language { get; set; }
    }
}
